import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import MainContainer from "@/components/MainContainer";
import SupabaseProviders from "@/providers/SupabaseProviders";
import UserProvider from "@/providers/UserProvider";
import ModalProvider from "@/providers/ModalProvider";
import React from "react";

const poppins = Poppins({
  weight: ["100", "900"],
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Poppins({
  weight: ["100", "900"],
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
      <body className={`${poppins.variable} ${geistMono.variable}`}>

      <SupabaseProviders>
          <UserProvider>
              <ModalProvider/>
              <MainContainer>{children}</MainContainer>
          </UserProvider>
      </SupabaseProviders>
      </body>
      </html>
  );
}
